//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.Database
{

    public partial class DataImport : ImportParams
    {
        decimal fRowDifference;
        public decimal RowDifference
        {
            get { return fRowDifference; }
            set { SetPropertyValue<decimal>(nameof(RowDifference), ref fRowDifference, value); }
        }
        decimal fAmountDifference;
        public decimal AmountDifference
        {
            get { return fAmountDifference; }
            set { SetPropertyValue<decimal>(nameof(AmountDifference), ref fAmountDifference, value); }
        }
        string fErrorMessage;
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
        DXApplication1.Module.Import.ERPSystem fERPSystem;
        public DXApplication1.Module.Import.ERPSystem ERPSystem
        {
            get { return fERPSystem; }
            set { SetPropertyValue<DXApplication1.Module.Import.ERPSystem>(nameof(ERPSystem), ref fERPSystem, value); }
        }
        DXApplication1.Module.Import.ImportStatus fImportStatus;
        public DXApplication1.Module.Import.ImportStatus ImportStatus
        {
            get { return fImportStatus; }
            set { SetPropertyValue<DXApplication1.Module.Import.ImportStatus>(nameof(ImportStatus), ref fImportStatus, value); }
        }
    }

}
