//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.Database
{

    public partial class ImportParams : XPObject
    {
        string fCustomer;
        public string Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<string>(nameof(Customer), ref fCustomer, value); }
        }
        string fAuditYear;
        public string AuditYear
        {
            get { return fAuditYear; }
            set { SetPropertyValue<string>(nameof(AuditYear), ref fAuditYear, value); }
        }
        string fCompanyCode;
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>(nameof(CompanyCode), ref fCompanyCode, value); }
        }
    }

}
