//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.Database
{

    [Persistent(@"invoice")]
    public partial class Invoice : XPObject
    {
        DateTime fInvoiceDate;
        [Persistent(@"True")]
        [DevExpress.Xpo.DisplayName(@"Invoice Date")]
        public DateTime InvoiceDate
        {
            get { return fInvoiceDate; }
            set { SetPropertyValue<DateTime>(nameof(InvoiceDate), ref fInvoiceDate, value); }
        }
        string fInvoiceNumber;
        [Size(15)]
        [Persistent(@"Number")]
        [DevExpress.Persistent.Validation.RuleRequiredField]
        public string InvoiceNumber
        {
            get { return fInvoiceNumber; }
            set { SetPropertyValue<string>(nameof(InvoiceNumber), ref fInvoiceNumber, value); }
        }
        Customer fCustomer;
        [Size(38)]
        [Association(@"InvoiceReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>(nameof(DueDate), ref fDueDate, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        double fTax;
        [ColumnDefaultValue(0)]
        public double Tax
        {
            get { return fTax; }
            set { SetPropertyValue<double>(nameof(Tax), ref fTax, value); }
        }
    }

}
