//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.Database
{

    public partial class MLDataSet : ImportParams
    {
        string fDocumentNumber;
        public string DocumentNumber
        {
            get { return fDocumentNumber; }
            set { SetPropertyValue<string>(nameof(DocumentNumber), ref fDocumentNumber, value); }
        }
        DateTime fBookingDate;
        public DateTime BookingDate
        {
            get { return fBookingDate; }
            set { SetPropertyValue<DateTime>(nameof(BookingDate), ref fBookingDate, value); }
        }
        DateTime fRecordingDate;
        public DateTime RecordingDate
        {
            get { return fRecordingDate; }
            set { SetPropertyValue<DateTime>(nameof(RecordingDate), ref fRecordingDate, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        string fBookingIndicator;
        public string BookingIndicator
        {
            get { return fBookingIndicator; }
            set { SetPropertyValue<string>(nameof(BookingIndicator), ref fBookingIndicator, value); }
        }
        string fAccount;
        public string Account
        {
            get { return fAccount; }
            set { SetPropertyValue<string>(nameof(Account), ref fAccount, value); }
        }
        string fAccountName;
        public string AccountName
        {
            get { return fAccountName; }
            set { SetPropertyValue<string>(nameof(AccountName), ref fAccountName, value); }
        }
        string fUser;
        public string User
        {
            get { return fUser; }
            set { SetPropertyValue<string>(nameof(User), ref fUser, value); }
        }
        string fCurrency;
        public string Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<string>(nameof(Currency), ref fCurrency, value); }
        }
        string fTaxKey;
        public string TaxKey
        {
            get { return fTaxKey; }
            set { SetPropertyValue<string>(nameof(TaxKey), ref fTaxKey, value); }
        }
    }

}
