//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication1.Module.BusinessObjects.Database
{

    [Persistent(@"order")]
    public partial class Order : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>(nameof(Oid), ref fOid, value); }
        }
        string fOrderno;
        [Persistent(@"OrderNo")]
        public string Orderno
        {
            get { return fOrderno; }
            set { SetPropertyValue<string>(nameof(Orderno), ref fOrderno, value); }
        }
        DateTime fOrderdate;
        [Persistent(@"OrderDate")]
        public DateTime Orderdate
        {
            get { return fOrderdate; }
            set { SetPropertyValue<DateTime>(nameof(Orderdate), ref fOrderdate, value); }
        }
        decimal fTotalamount;
        [Persistent(@"TotalAmount")]
        public decimal Totalamount
        {
            get { return fTotalamount; }
            set { SetPropertyValue<decimal>(nameof(Totalamount), ref fTotalamount, value); }
        }
        Customer fCustomer;
        [Size(38)]
        [Association(@"OrderReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
    }

}
